name: Mobius Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: default
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - name: nmake
      run: nmake

    - name: install nsis
      run: |
        iwr -useb get.scoop.sh -outfile 'install.ps1'
        .\install.ps1 -RunAsAdmin
        scoop update
        scoop bucket add extras
        scoop install nsis

    - name: create x64 installer
      run: makensis /V4 src/installx64/mobius.nsi

    - name: pre-release
      if: ${{ contains(github.ref_name, 'rc') }}
      uses: ncipollo/release-action@v1
      with:
        prerelease: true
        artifacts: "src/mobius/mobius.exe,src/mobius/MobiusVst2.dll,src/installx64/Install Mobius 2 (64-bit).exe"

    - name: full release
      if: ${{ ! contains(github.ref_name, 'rc') }}
      uses: ncipollo/release-action@v1
      with:
        artifacts: "src/mobius/mobius.exe,src/mobius/MobiusVst2.dll,src/installx64/Install Mobius 2 (64-bit).exe"
