name: Mobius Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: default
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
    - name: nmake
      run: nmake
    - name: uploads build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mobius x86
        path: |
          src/mobius/mobius.exe
          src/mobius/MobiusVst2.dll
        retention-days: 5
